export { default as Header } from './header'
export { default as Footer } from './footer'
export { default as BannerFullWidth } from './banner/BannerFullWidth'
export { default as Pricing } from './sections/pricing'
export { default as Suscription } from './sections/sucription'
export { default as Apply } from './sections/apply'
